# Generated by Django 5.2 on 2025-04-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='modal_images/')),
                ('link', models.URLField(blank=True, help_text='لینک مرتبط با اطلاع\u200cرسانی', null=True)),
                ('content', models.TextField()),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('individual', models.CharField(blank=True, help_text=' فرد ', max_length=255, null=True)),
                ('user_group', models.CharField(help_text='گروه کاربران هدف', max_length=255)),
                ('action', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'تبلیغات',
                'verbose_name_plural': 'تبلیغات',
            },
        ),
        migrations.CreateModel(
            name='ContentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='modal_images/')),
                ('link', models.URLField(blank=True, help_text='لینک مرتبط با اطلاع\u200cرسانی', null=True)),
                ('content', models.TextField()),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('individual', models.CharField(blank=True, help_text=' فرد ', max_length=255, null=True)),
                ('user_group', models.CharField(help_text='گروه کاربران هدف', max_length=255)),
                ('action', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'محتوا',
                'verbose_name_plural': 'محتوا',
            },
        ),
        migrations.CreateModel(
            name='ModalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='modal_images/')),
                ('link', models.URLField(blank=True, help_text='لینک مرتبط با اطلاع\u200cرسانی', null=True)),
                ('content', models.TextField()),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('individual', models.CharField(blank=True, help_text=' فرد ', max_length=255, null=True)),
                ('user_group', models.CharField(help_text='گروه کاربران هدف', max_length=255)),
                ('action', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'مودال',
                'verbose_name_plural': 'مودال',
            },
        ),
        migrations.CreateModel(
            name='NotificationSms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('user_group', models.CharField(help_text='گروه کاربران هدف', max_length=255)),
                ('is_selected', models.BooleanField(default=False)),
                ('action', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'پیامک',
                'verbose_name_plural': 'پیامک',
            },
        ),
    ]
