# Generated by Django 5.1.6 on 2025-03-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True,
                 null=True, upload_to='modal_images/')),
                ('link', models.URLField(blank=True,
                 help_text='لینک مرتبط با اطلاع\u200cرسانی', null=True)),
                ('content', models.TextField()),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('individual', models.CharField(blank=True,
                 help_text=' فرد \u200c', max_length=255, null=True)),
                ('user_group', models.CharField(
                    help_text='گروه کاربران هدف', max_length=255)),
                ('action', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSms',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('user_group', models.CharField(
                    help_text='گروه کاربران هدف', max_length=255)),
                ('is_selected', models.BooleanField(default=False)),
                ('action', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
