# Generated by Django 5.1.6 on 2025-04-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notif', '0002_advertisementnotification_contentnotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisementnotification',
            options={'verbose_name': 'تبلیغات', 'verbose_name_plural': 'تبلیغات'},
        ),
        migrations.AlterModelOptions(
            name='contentnotification',
            options={'verbose_name': 'محتوا', 'verbose_name_plural': 'محتوا'},
        ),
        migrations.AlterModelOptions(
            name='modalnotification',
            options={'verbose_name': 'مودال', 'verbose_name_plural': 'مودال'},
        ),
        migrations.AlterModelOptions(
            name='notificationsms',
            options={'verbose_name': 'پیامک', 'verbose_name_plural': 'پیامک'},
        ),
    ]
