# Generated by Django 5.1.6 on 2025-04-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notif', '0003_alter_advertisementnotification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementnotification',
            name='individual',
            field=models.CharField(blank=True, help_text=' فرد ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contentnotification',
            name='individual',
            field=models.CharField(blank=True, help_text=' فرد ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modalnotification',
            name='individual',
            field=models.CharField(blank=True, help_text=' فرد ', max_length=255, null=True),
        ),
    ]
