# Generated by Django 5.2 on 2025-04-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='messenger',
            field=models.CharField(max_length=255, verbose_name='اطلاع رسانی'),
        ),
    ]
