# Generated by Django 5.1.6 on 2025-03-05 15:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='messenger',
            field=models.CharField(max_length=255, verbose_name='پیام رسان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='operations',
            field=models.CharField(choices=[('created', 'ایجاد'), ('edited', 'ویرایش'), ('not_created', 'ایجاد نشده')], max_length=12, verbose_name='عملیات'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'خریدار'), ('seller', 'فروشنده'), ('marketer', 'بازاریاب')], max_length=10, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال')], max_length=8, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_status',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='وضعیت کیف پول'),
        ),
    ]
