# Generated by Django 5.2 on 2025-04-22 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_customuser_messenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wallet_status',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='وضعیت کیف پول'),
        ),
    ]
