# Generated by Django 5.1.6 on 2025-03-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_user_current_location_alter_user_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_location',
        ),
    ]
