# Generated by Django 5.1.6 on 2025-03-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
