# Generated by Django 5.1.6 on 2025-03-06 16:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0005_delete_user'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='نام')),
                ('last_name', models.CharField(max_length=255, verbose_name='نام خانوادگی')),
                ('role', models.CharField(choices=[('buyer', 'خریدار'), ('seller', 'فروشنده'), ('marketer', 'بازاریاب')], max_length=10, verbose_name='نقش')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('national_id', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('wallet_status', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='وضعیت کیف پول')),
                ('messenger', models.CharField(max_length=255, verbose_name='پیام رسان')),
                ('operations', models.CharField(choices=[('created', 'ایجاد'), ('edited', 'ویرایش'), ('not_created', 'ایجاد نشده')], max_length=12, verbose_name='عملیات')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال')], max_length=8, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city', verbose_name='شهر')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region', verbose_name='استان')),
            ],
        ),
    ]
