# Generated by Django 5.1.6 on 2025-04-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'اکانت', 'verbose_name_plural': ' اکانت'},
        ),
    ]
