# Generated by Django 5.0 on 2025-04-07 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='is_active',
        ),
    ]
