# Generated by Django 5.1.6 on 2025-03-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('name', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cover_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacture_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('sale_status', models.CharField(max_length=50)),
                ('marketer_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('turnover', models.IntegerField()),
                ('operations', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
