# Generated by Django 5.2 on 2025-04-20 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='product_images/', verbose_name='تصویر اصلی')),
                ('barcode', models.CharField(max_length=100, null=True, verbose_name='بارکد')),
                ('name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('stock', models.IntegerField(verbose_name='موجودی')),
                ('unit', models.CharField(max_length=50, verbose_name='واحد')),
                ('stock_warning', models.IntegerField(null=True, verbose_name='هشدار موجودی')),
                ('category', models.CharField(max_length=255, verbose_name='دسته\u200cبندی')),
                ('brand', models.CharField(max_length=255, verbose_name='برند')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت خرید')),
                ('cover_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت روی جلد')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت فروش')),
                ('manufacture_date', models.DateField(verbose_name='تاریخ تولید')),
                ('expiration_date', models.DateField(verbose_name='تاریخ انقضا')),
                ('expiration_threshold', models.IntegerField(null=True, verbose_name='آستانه انقضا')),
                ('sale_status', models.CharField(choices=[('normal_sale', 'فروش عادی'), ('not_for_sale', 'عدم فروش محصول'), ('not_displayed', 'عدم نمایش محصول')], max_length=20, verbose_name='وضعیت فروش')),
                ('marketer_profit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سود بازاریاب')),
                ('turnover', models.IntegerField(verbose_name='گردش کالا')),
                ('operations', models.CharField(choices=[('edit_stock', 'ویرایش موجودی'), ('edit_price', 'ویرایش قیمت'), ('register', 'ثبت')], max_length=20, verbose_name='عملیات')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='product_extra_images/', verbose_name='تصویر اضافی')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='Product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر اضافی محصول',
                'verbose_name_plural': 'تصاویر اضافی محصولات',
            },
        ),
    ]
