# Generated by Django 5.0 on 2025-04-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_product_operations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.AddField(
            model_name='product',
            name='expiration_threshold',
            field=models.IntegerField(null=True, verbose_name='آستانه انقضا'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_warning',
            field=models.IntegerField(null=True, verbose_name='هشدار موجودی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=255, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت روی جلد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products/', verbose_name='تصویر محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacture_date',
            field=models.DateField(verbose_name='تاریخ تولید'),
        ),
        migrations.AlterField(
            model_name='product',
            name='marketer_profit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سود بازاریاب'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='operations',
            field=models.CharField(choices=[('edit_stock', 'ویرایش موجودی'), ('edit_price', 'ویرایش قیمت'), ('register', 'ثبت')], max_length=20, verbose_name='عملیات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت خرید'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت فروش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_status',
            field=models.CharField(choices=[('normal_sale', 'فروش عادی'), ('not_for_sale', 'عدم فروش محصول'), ('not_displayed', 'عدم نمایش محصول')], max_length=20, verbose_name='وضعیت فروش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='turnover',
            field=models.IntegerField(verbose_name='گردش کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=50, verbose_name='واحد'),
        ),
    ]
