# Generated by Django 5.0 on 2025-04-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_product_options_remove_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='بارکد'),
        ),
    ]
