# Generated by Django 5.1.6 on 2025-03-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('national_id', models.CharField(max_length=10, unique=True)),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال')], max_length=20)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('notifications', models.TextField(blank=True)),
                ('actions', models.TextField(blank=True)),
                ('requires_action', models.BooleanField(default=False)),
                ('total_paid_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('payment_document', models.ImageField(blank=True, upload_to='marketer_documents/payments/')),
                ('action_details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('store_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('national_id', models.CharField(max_length=10, unique=True)),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('financial_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('history', models.TextField(blank=True)),
                ('notifications', models.TextField(blank=True)),
            ],
        ),
    ]
