# Generated by Django 5.2 on 2025-04-20 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanciallySettled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, verbose_name='شماره سفارش')),
                ('purchase_type', models.CharField(max_length=50, verbose_name='نوع خرید')),
                ('product_items', models.TextField(verbose_name='اقلام کالایی')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ کل')),
                ('order_date', models.DateField(verbose_name='تاریخ سفارش')),
                ('delivery_date', models.DateField(verbose_name='تاریخ تحویل')),
                ('settlement_date', models.DateField(verbose_name=' تاریخ تصویه حساب')),
                ('settlement_info', models.TextField(choices=[('cash', 'نقد'), ('check', 'چک'), ('promissory_note', 'سفته'), ('Wallet', 'کیف پول'), ('Gateway', 'درگاه'), ('Cardreader', 'کارتخوان')], verbose_name='اطلاعات تسویه')),
                ('document', models.FileField(upload_to='documents/', verbose_name='سند')),
                ('operation', models.CharField(max_length=50, verbose_name='عملیات')),
                ('product_name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='فی')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='جمع مبلغ')),
                ('settlement_type', models.CharField(max_length=50, verbose_name='نوع تسویه')),
                ('referred_to', models.CharField(max_length=50, verbose_name='ارجاع به ')),
                ('explainer_name', models.CharField(max_length=50, verbose_name='نام توضیح کننده')),
            ],
            options={
                'verbose_name': 'مالی خریدار تسویه شده',
                'verbose_name_plural': 'مالی خریدار تسویه شده',
            },
        ),
        migrations.CreateModel(
            name='HistoryMarketerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(max_length=255, verbose_name='سابقه')),
                ('is_selected', models.BooleanField(default=False, verbose_name='انتخاب شده')),
                ('total_paid_profit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مجموع سود پرداخت شده')),
                ('document', models.FileField(upload_to='documents/', verbose_name='سند')),
                ('more_details', models.TextField(blank=True, verbose_name='نمایش بیشتر')),
                ('payment_date', models.DateField(verbose_name='تاریخ پرداخت')),
            ],
            options={
                'verbose_name': ' سابقه بازاریاب  ',
                'verbose_name_plural': ' سابقه بازاریاب  ',
            },
        ),
        migrations.CreateModel(
            name='MarketerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('role', models.CharField(max_length=50, verbose_name='نقش')),
                ('contact_number', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('province', models.CharField(max_length=50, verbose_name='استان')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال')], max_length=20, verbose_name='وضعیت')),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='موجودی کیف پول')),
                ('notifications', models.TextField(blank=True, verbose_name='نوتیفیکیشن\u200cها')),
                ('actions', models.TextField(blank=True, verbose_name='عملیات')),
                ('requires_action', models.BooleanField(default=False)),
                ('total_paid_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('payment_document', models.ImageField(blank=True, upload_to='marketer_documents/payments/')),
                ('action_details', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'مالی بازاریاب',
                'verbose_name_plural': 'مالی بازاریاب\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('store_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('national_id', models.CharField(max_length=10, unique=True)),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('financial_limit', models.DecimalField(choices=[('cash', 'نقد'), ('check', 'چک'), ('promissory_note', 'سفته'), ('Wallet', 'کیف پول'), ('Gateway', 'درگاه'), ('Cardreader', 'کارتخوان')], decimal_places=2, default=0.0, max_digits=15)),
                ('history', models.TextField(blank=True)),
                ('notifications', models.TextField(blank=True)),
                ('operations', models.CharField(choices=[('created', 'ایجاد'), ('edited', 'ویرایش'), ('not_created', 'ایجاد نشده')], default='register', max_length=20)),
            ],
            options={
                'verbose_name': ' مالی اصلی',
                'verbose_name_plural': ' مالی اصلی',
            },
        ),
        migrations.CreateModel(
            name='ProductPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Payment_images/')),
                ('product_name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('stock', models.IntegerField(verbose_name='موجودی')),
                ('unit', models.CharField(max_length=50, verbose_name='واحد')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت خرید')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت فروش')),
                ('cover_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت روی جلد')),
                ('operation', models.TextField(blank=True, verbose_name='عملیات')),
                ('profit_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد سود')),
                ('inventory_turnover', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='گردش کالا')),
                ('sales_history', models.TextField(blank=True, verbose_name='سابقه فروش')),
                ('actions', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'سابقه محصول',
                'verbose_name_plural': 'سابقه محصول',
            },
        ),
        migrations.CreateModel(
            name='RequestActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('store_name', models.CharField(max_length=100, verbose_name='نام فروشگاه')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('national_id', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('province', models.CharField(max_length=50, verbose_name='استان')),
                ('location', models.TextField(verbose_name='لوکیشن')),
                ('request', models.TextField(verbose_name='درخواست')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('referred_to', models.CharField(max_length=100, verbose_name='ارجاع به')),
                ('action', models.TextField(verbose_name='اقدام')),
            ],
            options={
                'verbose_name': 'ثبت درخواست',
                'verbose_name_plural': 'ثبت درخواست\u200cها',
            },
        ),
        migrations.CreateModel(
            name='BuyerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('store_name', models.CharField(max_length=255, verbose_name='نام فروشگاه')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('national_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('location', models.TextField(verbose_name='لوکیشن')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='بدهی')),
                ('financial_limit', models.DecimalField(choices=[('cash', 'نقد'), ('check', 'چک'), ('promissory_note', 'سفته'), ('Wallet', 'کیف پول'), ('Gateway', 'درگاه'), ('Cardreader', 'کارتخوان')], decimal_places=2, max_digits=10, verbose_name='محدودیت مالی')),
                ('history', models.TextField(blank=True, verbose_name='سابقه')),
                ('messenger', models.CharField(blank=True, max_length=50, verbose_name='پیام رسان')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='Payment.payment', verbose_name=' مالی ')),
            ],
            options={
                'verbose_name': 'مالی خریدار',
                'verbose_name_plural': 'مالی خریدار',
            },
        ),
    ]
