# Generated by Django 5.1.6 on 2025-03-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryMarketerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(max_length=255, verbose_name='سابقه')),
                ('is_selected', models.BooleanField(default=False, verbose_name='انتخاب شده')),
                ('total_paid_profit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مجموع سود پرداخت شده')),
                ('document', models.FileField(upload_to='documents/', verbose_name='سند')),
                ('more_details', models.TextField(blank=True, verbose_name='نمایش بیشتر')),
                ('payment_date', models.DateField(verbose_name='تاریخ پرداخت')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('stock', models.IntegerField(verbose_name='موجودی')),
                ('unit', models.CharField(max_length=50, verbose_name='واحد')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت خرید')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت فروش')),
                ('cover_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت روی جلد')),
                ('operation', models.TextField(blank=True, verbose_name='عملیات')),
                ('profit_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد سود')),
                ('inventory_turnover', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='گردش کالا')),
                ('sales_history', models.TextField(blank=True, verbose_name='سابقه فروش')),
            ],
        ),
    ]
