# Generated by Django 5.1.6 on 2025-04-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_historymarketerpayment_productpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('store_name', models.CharField(max_length=255, verbose_name='نام فروشگاه')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('national_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('location', models.TextField(verbose_name='لوکیشن')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='بدهی')),
                ('financial_limit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='محدودیت مالی')),
                ('history', models.TextField(blank=True, verbose_name='سابقه')),
                ('messenger', models.CharField(blank=True, max_length=50, verbose_name='پیام رسان')),
            ],
        ),
        migrations.AddField(
            model_name='productpayment',
            name='actions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Payment_images/'),
        ),
    ]
