# Generated by Django 5.1.6 on 2025-04-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_buyerpayment_productpayment_actions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerpayment',
            options={'verbose_name': 'مالی خریدار', 'verbose_name_plural': 'مالی خریدار'},
        ),
        migrations.AlterModelOptions(
            name='historymarketerpayment',
            options={'verbose_name': ' سابقه بازاریاب  ', 'verbose_name_plural': ' سابقه بازاریاب  '},
        ),
        migrations.AlterModelOptions(
            name='marketerpayment',
            options={'verbose_name': 'مالی بازاریاب', 'verbose_name_plural': 'مالی بازاریاب'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': ' مالی اصلی', 'verbose_name_plural': ' مالی اصلی'},
        ),
        migrations.AlterModelOptions(
            name='productpayment',
            options={'verbose_name': 'سابقه محصول', 'verbose_name_plural': 'سابقه محصول'},
        ),
    ]
