# Generated by Django 5.1.6 on 2025-04-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_alter_buyerpayment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='operations',
            field=models.CharField(choices=[('register', 'ثبت'), ('action', 'اقدام'), ('edit_stock', 'ویرایش موجودی'), ('edit_price', 'ویرایش قیمت'), ('normal_sale', 'فروش عادی'), ('not_for_sale', 'عدم فروش محصول'), ('not_displayed', 'عدم نمایش محصول')], default='register', max_length=20),
        ),
    ]
