# Generated by Django 5.1.6 on 2025-04-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0006_financiallysettled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financiallysettled',
            name='settlement_info',
            field=models.TextField(choices=[('cash', 'نقد'), ('check', 'چک'), ('promissory_note', 'سفته'), ('Wallet', 'کیف پول'), ('Gateway', 'درگاه'), ('Cardreader', 'کارتخوان')], verbose_name='اطلاعات تسویه'),
        ),
    ]
