# Generated by Django 5.1.6 on 2025-04-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0007_alter_financiallysettled_settlement_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('store_name', models.CharField(max_length=100, verbose_name='نام فروشگاه')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('national_id', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('province', models.CharField(max_length=50, verbose_name='استان')),
                ('location', models.TextField(verbose_name='لوکیشن')),
                ('request', models.TextField(verbose_name='درخواست')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('referred_to', models.CharField(max_length=100, verbose_name='ارجاع به')),
                ('action', models.TextField(verbose_name='اقدام')),
            ],
            options={
                'verbose_name': 'ثبت درخواست',
                'verbose_name_plural': 'ثبت درخواست\u200cها',
            },
        ),
    ]
