# Generated by Django 5.0 on 2025-04-09 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0008_requestactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerpayment',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='Payment.payment', verbose_name=' مالی '),
        ),
    ]
