# Generated by Django 5.0 on 2025-04-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0009_buyerpayment_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerpayment',
            name='financial_limit',
            field=models.DecimalField(choices=[('cash', 'نقد'), ('check', 'چک'), ('promissory_note', 'سفته'), ('Wallet', 'کیف پول'), ('Gateway', 'درگاه'), ('Cardreader', 'کارتخوان')], decimal_places=2, max_digits=10, verbose_name='محدودیت مالی'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='financial_limit',
            field=models.DecimalField(choices=[('cash', 'نقد'), ('check', 'چک'), ('promissory_note', 'سفته'), ('Wallet', 'کیف پول'), ('Gateway', 'درگاه'), ('Cardreader', 'کارتخوان')], decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
