# Generated by Django 5.0 on 2025-04-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0010_alter_buyerpayment_financial_limit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketerpayment',
            options={'verbose_name': 'مالی بازاریاب', 'verbose_name_plural': 'مالی بازاریاب\u200cها'},
        ),
        migrations.AlterField(
            model_name='marketerpayment',
            name='actions',
            field=models.TextField(blank=True, verbose_name='عملیات'),
        ),
        migrations.AlterField(
            model_name='marketerpayment',
            name='city',
            field=models.CharField(max_length=50, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='marketerpayment',
            name='contact_number',
            field=models.CharField(max_length=20, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='marketerpayment',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='marketerpayment',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='marketerpayment',
            name='national_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='marketerpayment',
            name='notifications',
            field=models.TextField(blank=True, verbose_name='نوتیفیکیشن\u200cها'),
        ),
        migrations.AlterField(
            model_name='marketerpayment',
            name='province',
            field=models.CharField(max_length=50, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='marketerpayment',
            name='role',
            field=models.CharField(max_length=50, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='marketerpayment',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال')], max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='marketerpayment',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='موجودی کیف پول'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='operations',
            field=models.CharField(choices=[('created', 'ایجاد'), ('edited', 'ویرایش'), ('not_created', 'ایجاد نشده')], default='register', max_length=20),
        ),
    ]
