# Generated by Django 5.2 on 2025-04-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory_images/')),
                ('product_name', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('stock_alert', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cover_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('expiry_threshold', models.IntegerField(blank=True, help_text='Days before expiry to alert', null=True)),
                ('sale_status', models.CharField(choices=[('Available', 'Available'), ('Sold Out', 'Sold Out')], max_length=50)),
                ('sale_range', models.CharField(blank=True, max_length=255, null=True)),
                ('marketer_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('operations', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'موجوی',
                'verbose_name_plural': ' موجوی',
            },
        ),
    ]
