# Generated by Django 5.1.6 on 2025-04-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'موجوی', 'verbose_name_plural': ' موجوی'},
        ),
    ]
