# Generated by Django 5.2 on 2025-04-20 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.BooleanField(default=False, verbose_name='تأیید شماره تماس')),
                ('national_id', models.BooleanField(default=False, verbose_name='تأیید کد ملی')),
                ('id_card_image', models.ImageField(upload_to='auth_documents/id_cards/', verbose_name='تصویر کارت ملی')),
                ('birth_certificate_image', models.ImageField(upload_to='auth_documents/birth_certificates/', verbose_name='تصویر شناسنامه')),
                ('guarantee_or_check_contract', models.FileField(upload_to='auth_documents/contracts/', verbose_name='قرارداد ضمانت یا چک')),
            ],
            options={
                'verbose_name': 'احراز هویت خریدار',
                'verbose_name_plural': 'احراز هویت خریداران',
            },
        ),
        migrations.CreateModel(
            name='BuyerCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, verbose_name='شماره سفارش')),
                ('purchase_type', models.CharField(max_length=50, verbose_name='نوع خرید')),
                ('order_date', models.DateTimeField(verbose_name='تاریخ سفارش')),
                ('delivery_date', models.DateTimeField(verbose_name='تاریخ تحویل')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ کل')),
                ('settlement_type', models.CharField(max_length=50, verbose_name='نوع تسویه')),
                ('product_name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='فی')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبد خرید\u200cها',
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('purchase_type', models.CharField(max_length=50, verbose_name='نوع خرید')),
                ('order_date', models.DateTimeField(verbose_name='تاریخ سفارش')),
                ('delivery_date', models.DateTimeField(verbose_name='تاریخ تحویل')),
                ('settlement_date', models.DateTimeField(verbose_name='تاریخ تسویه حساب')),
                ('settlement_details', models.TextField(verbose_name='اطلاعات تسویه')),
            ],
            options={
                'verbose_name': 'تاریخچه خرید',
                'verbose_name_plural': 'تاریخچه\u200cهای خرید',
            },
        ),
        migrations.CreateModel(
            name='Shopper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('store_name', models.CharField(max_length=255, verbose_name='نام فروشگاه')),
                ('contact_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال')], max_length=20, verbose_name='وضعیت')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('location', models.TextField(verbose_name='موقعیت')),
                ('shopping_cart', models.TextField(blank=True, verbose_name='سبد خرید')),
                ('financial_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='محدودیت مالی')),
                ('history', models.TextField(blank=True, verbose_name='سابقه')),
                ('score', models.IntegerField(null=True)),
                ('notifications', models.TextField(blank=True, verbose_name='نوتیفیکیشن\u200cها')),
                ('is_authenticated', models.BooleanField(default=False, verbose_name='احراز هویت')),
                ('actions', models.TextField(blank=True, verbose_name='عملیات')),
            ],
            options={
                'verbose_name': 'پروفایل خریدار ',
                'verbose_name_plural': 'پروفایل\u200c خریدار',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='نام')),
                ('last_name', models.CharField(max_length=255, verbose_name='نام خانوادگی')),
                ('store_name', models.CharField(max_length=255, verbose_name='نام فروشگاه')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('national_id', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال')], max_length=8, verbose_name='وضعیت')),
                ('shopping_cart', models.TextField(verbose_name='سبد خرید')),
                ('financial_limit', models.CharField(choices=[('cash', 'نقد'), ('check', 'چک'), ('promissory_note', 'سفته'), ('Wallet', 'کیف پول'), ('Gateway', 'درگاه'), ('Cardreader', 'کارتخوان')], max_length=15, verbose_name='محدودیت مالی')),
                ('purchase_history', models.TextField(verbose_name='سابقه خرید')),
                ('messenger', models.CharField(max_length=255, verbose_name='پیام\u200cرسان')),
                ('authentication', models.BooleanField(default=False, verbose_name='احراز هویت')),
                ('operations', models.CharField(choices=[('edit_stock', 'ویرایش موجودی'), ('edit_price', 'ویرایش قیمت'), ('register', 'ثبت')], default='register', max_length=12, verbose_name='عملیات')),
                ('current_location', models.CharField(max_length=255, null=True, verbose_name='موقعیت فعلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city', verbose_name='شهر')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'خریدار',
                'verbose_name_plural': 'خریداران',
            },
        ),
        migrations.CreateModel(
            name='BuyerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت واحد')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Shopper.buyercart', verbose_name='سبد خرید')),
            ],
            options={
                'verbose_name': 'محصول خریدار',
                'verbose_name_plural': 'محصولات خریدار',
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت واحد')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='جمع کل')),
                ('purchase_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Shopper.purchasehistory', verbose_name='سابقه خرید')),
            ],
            options={
                'verbose_name': 'جزئیات محصول در سابقه خرید',
                'verbose_name_plural': 'جزئیات محصولات در سابقه خرید',
            },
        ),
    ]
