# Generated by Django 5.1.6 on 2025-03-24 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopper', '0005_buyercart'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=20)),
                ('purchase_type', models.CharField(max_length=50)),
                ('order_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('settlement_date', models.DateTimeField()),
                ('settlement_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BuyerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Shopper.buyercart')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHistoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Shopper.purchasehistory')),
            ],
        ),
    ]
