# Generated by Django 5.1.6 on 2025-03-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopper', '0006_purchasehistory_buyerproduct_purchasehistoryproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=20)),
                ('national_id', models.CharField(max_length=10, unique=True)),
                ('id_card_image', models.ImageField(upload_to='auth_documents/id_cards/')),
                ('birth_certificate_image', models.ImageField(upload_to='auth_documents/birth_certificates/')),
                ('guarantee_or_check_contract', models.FileField(upload_to='auth_documents/contracts/')),
            ],
        ),
    ]
