# Generated by Django 5.1.6 on 2025-04-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopper', '0007_buyerauthentication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'verbose_name': 'خریدار', 'verbose_name_plural': 'خریدار'},
        ),
        migrations.AlterModelOptions(
            name='buyerauthentication',
            options={'verbose_name': 'احراز هویت خریدار', 'verbose_name_plural': 'احراز هویت خریدار'},
        ),
        migrations.AlterModelOptions(
            name='buyercart',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد خرید'},
        ),
        migrations.AlterModelOptions(
            name='buyerproduct',
            options={'verbose_name': 'خریدار محصول', 'verbose_name_plural': 'خریدار محصول'},
        ),
        migrations.AlterModelOptions(
            name='purchasehistory',
            options={'verbose_name': 'تاریخچه خرید', 'verbose_name_plural': 'تاریخچه خرید'},
        ),
        migrations.AlterModelOptions(
            name='purchasehistoryproduct',
            options={'verbose_name': 'تاریخچه خرید محصول', 'verbose_name_plural': 'تاریخچه خرید محصول'},
        ),
    ]
