# Generated by Django 5.1.6 on 2025-04-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopper', '0008_alter_buyer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('store_name', models.CharField(max_length=255, verbose_name='نام فروشگاه')),
                ('contact_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال')], max_length=20, verbose_name='وضعیت')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('location', models.TextField(verbose_name='موقعیت')),
                ('shopping_cart', models.TextField(blank=True, verbose_name='سبد خرید')),
                ('financial_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='محدودیت مالی')),
                ('history', models.TextField(blank=True, verbose_name='سابقه')),
                ('notifications', models.TextField(blank=True, verbose_name='نوتیفیکیشن\u200cها')),
                ('is_authenticated', models.BooleanField(default=False, verbose_name='احراز هویت')),
                ('actions', models.TextField(blank=True, verbose_name='عملیات')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل\u200cهای کاربران',
            },
        ),
    ]
