# Generated by Django 5.1.6 on 2025-04-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopper', '0009_shopper'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopper',
            options={'verbose_name': 'پروفایل خریدار ', 'verbose_name_plural': 'پروفایل\u200c خریدار'},
        ),
    ]
