# Generated by Django 5.1.6 on 2025-04-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopper', '0011_alter_buyer_financial_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='operations',
            field=models.CharField(choices=[('created', 'ایجاد'), ('edited', 'ویرایش'), ('not_created', 'ایجاد نشده')], default='register', max_length=12),
        ),
    ]
