# Generated by Django 5.1.6 on 2025-04-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopper', '0012_alter_buyer_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerauthentication',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
