# Generated by Django 5.0 on 2025-04-09 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopper', '0014_remove_buyerauthentication_is_verified_and_more'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'verbose_name': 'خریدار', 'verbose_name_plural': 'خریداران'},
        ),
        migrations.AlterField(
            model_name='buyer',
            name='authentication',
            field=models.BooleanField(default=False, verbose_name='احراز هویت'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='current_location',
            field=models.CharField(max_length=255, null=True, verbose_name='موقعیت فعلی'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='financial_limit',
            field=models.CharField(choices=[('cash', 'نقد'), ('check', 'چک'), ('promissory_note', 'سفته'), ('Wallet', 'کیف پول'), ('Gateway', 'درگاه'), ('Cardreader', 'کارتخوان')], max_length=15, verbose_name='محدودیت مالی'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='messenger',
            field=models.CharField(max_length=255, verbose_name='پیام\u200cرسان'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='national_id',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='operations',
            field=models.CharField(choices=[('edit_stock', 'ویرایش موجودی'), ('edit_price', 'ویرایش قیمت'), ('register', 'ثبت')], default='register', max_length=12, verbose_name='عملیات'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='purchase_history',
            field=models.TextField(verbose_name='سابقه خرید'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='shopping_cart',
            field=models.TextField(verbose_name='سبد خرید'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال')], max_length=8, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='store_name',
            field=models.CharField(max_length=255, verbose_name='نام فروشگاه'),
        ),
    ]
