# Generated by Django 5.0 on 2025-04-09 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopper', '0015_alter_buyer_options_alter_buyer_authentication_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerauthentication',
            options={'verbose_name': 'احراز هویت خریدار', 'verbose_name_plural': 'احراز هویت خریداران'},
        ),
        migrations.AlterModelOptions(
            name='buyercart',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد خرید\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='buyerproduct',
            options={'verbose_name': 'محصول خریدار', 'verbose_name_plural': 'محصولات خریدار'},
        ),
        migrations.AlterModelOptions(
            name='purchasehistory',
            options={'verbose_name': 'تاریخچه خرید', 'verbose_name_plural': 'تاریخچه\u200cهای خرید'},
        ),
        migrations.AlterModelOptions(
            name='purchasehistoryproduct',
            options={'verbose_name': 'جزئیات محصول در سابقه خرید', 'verbose_name_plural': 'جزئیات محصولات در سابقه خرید'},
        ),
        migrations.AlterField(
            model_name='buyerauthentication',
            name='birth_certificate_image',
            field=models.ImageField(upload_to='auth_documents/birth_certificates/', verbose_name='تصویر شناسنامه'),
        ),
        migrations.AlterField(
            model_name='buyerauthentication',
            name='contact_number',
            field=models.BooleanField(default=False, verbose_name='تأیید شماره تماس'),
        ),
        migrations.AlterField(
            model_name='buyerauthentication',
            name='guarantee_or_check_contract',
            field=models.FileField(upload_to='auth_documents/contracts/', verbose_name='قرارداد ضمانت یا چک'),
        ),
        migrations.AlterField(
            model_name='buyerauthentication',
            name='id_card_image',
            field=models.ImageField(upload_to='auth_documents/id_cards/', verbose_name='تصویر کارت ملی'),
        ),
        migrations.AlterField(
            model_name='buyerauthentication',
            name='national_id',
            field=models.BooleanField(default=False, verbose_name='تأیید کد ملی'),
        ),
        migrations.AlterField(
            model_name='buyercart',
            name='delivery_date',
            field=models.DateTimeField(verbose_name='تاریخ تحویل'),
        ),
        migrations.AlterField(
            model_name='buyercart',
            name='order_date',
            field=models.DateTimeField(verbose_name='تاریخ سفارش'),
        ),
        migrations.AlterField(
            model_name='buyercart',
            name='order_number',
            field=models.CharField(max_length=50, verbose_name='شماره سفارش'),
        ),
        migrations.AlterField(
            model_name='buyercart',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='buyercart',
            name='purchase_type',
            field=models.CharField(max_length=50, verbose_name='نوع خرید'),
        ),
        migrations.AlterField(
            model_name='buyercart',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='buyercart',
            name='settlement_type',
            field=models.CharField(max_length=50, verbose_name='نوع تسویه'),
        ),
        migrations.AlterField(
            model_name='buyercart',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ کل'),
        ),
        migrations.AlterField(
            model_name='buyercart',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='فی'),
        ),
        migrations.AlterField(
            model_name='buyerproduct',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Shopper.buyercart', verbose_name='سبد خرید'),
        ),
        migrations.AlterField(
            model_name='buyerproduct',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='buyerproduct',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='buyerproduct',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='contact_number',
            field=models.CharField(max_length=20, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='delivery_date',
            field=models.DateTimeField(verbose_name='تاریخ تحویل'),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='order_date',
            field=models.DateTimeField(verbose_name='تاریخ سفارش'),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='purchase_type',
            field=models.CharField(max_length=50, verbose_name='نوع خرید'),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='settlement_date',
            field=models.DateTimeField(verbose_name='تاریخ تسویه حساب'),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='settlement_details',
            field=models.TextField(verbose_name='اطلاعات تسویه'),
        ),
        migrations.AlterField(
            model_name='purchasehistoryproduct',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='purchasehistoryproduct',
            name='purchase_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Shopper.purchasehistory', verbose_name='سابقه خرید'),
        ),
        migrations.AlterField(
            model_name='purchasehistoryproduct',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='purchasehistoryproduct',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='جمع کل'),
        ),
        migrations.AlterField(
            model_name='purchasehistoryproduct',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت واحد'),
        ),
    ]
